name         'bigcommerce-ssl'
version      '0.0.1'
license      'MIT'
summary      'Install and manage SSL certificates and certificate authorities'
author       'Chris Boulton <chris@chrisboulton.com>'
source       'https://github.com/bigcommerce/puppet-ssl'
project_page 'https://github.com/bigcommerce/puppet-ssl'
